server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: cars-auctions
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:15432/cars_auctions}
    username: ${DATASOURCE_USERNAME:user}
    password: ${DATASOURCE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5673}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: AUTO
        concurrency: 3
        retry:
          enabled: true
          initial-interval: 100
          max-interval: 1000
          max-attempts: 5
          multiplier: 2
  flyway:
    enabled: true
