server:
  port: 8081

spring:
  application:
    name: cars-auctions
  datasource:
    url: jdbc:postgresql://localhost:15432/cars_auctions
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  quartz:
    job-store-type: jdbc
    jdbc:
      # TODO change
      initialize-schema: always
    properties:
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate